<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Verificacion extends Model
{
    protected $table='verificacion';
    protected $fillable = [
        'verificacionCodigo',
        'verificacionModelo',
        'verificacionNumEmpleado',
        'verificacionSerie',
        'verificacionNomUsuario',
        'verificacionAreaDepartamento',
        'verificacionMarca',
        'verificacionAsignacion',
        'verificacionFecha',
        'verificacionConcepto1',
        'verificacionConcepto2',
        'verificacionConcepto3',
        'verificacionConcepto4',
        'verificacionConcepto5',
        'verificacionConcepto6',
        'verificacionConcepto7',
        'verificacionConcepto8',
        'verificacionConcepto9',
        'verificacionConcepto10',
        'verificacionConcepto11',
        'verificacionConcepto12',
        'verificacionConcepto13',
        'verificacionConcepto14',
        'verificacionConcepto15',
        'verificacionConcepto16',
        'verificacionConcepto17',
        'verificacionConcepto18',
        'verificacionConcepto19',
        'verificacionConcepto20',
        'verificacionConcepto21',
        'verificacionConcepto22',
        'verificacionConcepto23',
        'verificacionConcepto24',
        'verificacionConcepto25',
        'verificacionConcepto26',
        'verificacionConcepto27',
        'verificacionConcepto28',
        'verificacionConcepto29',
        'verificacionConcepto30',
        'verificacionConcepto31',
        'verificacionConcepto32',
        'verificacionConcepto33',
        'verificacionConcepto34',
        'verificacionConcepto35',
        'verificacionConcepto36',
        'verificacionConcepto37',
        'verificacionConcepto38',
        'verificacionConcepto39',
        'verificacionConcepto40',
        'verificacionConcepto41',
        'verificacionConcepto42',
        'verificacionConcepto43',
        'verificacionConcepto44',
        'verificacionConcepto45',
        'verificacionConcepto46',
        'verificacionConcepto47',
        'verificacionConcepto48',
        'verificacionConceptoObservacion',
        'verificacionAccion',
        'verificacionResponsable',
        'verificacionFechaCumplimiento',
    ];
}

